os: linux
dist: bionic
language: node_js
node_js:
  - 10.12
  - lts/dubnium
  - lts/erbium
  - lts/*
  - node
before_install:
  # latest npm, gulp
  - npm i -g gulp-cli # npm yarn
  ## latest yarn
  # - curl -o- -L https://yarnpkg.com/install.sh | bash # -s -- --version [version]
  # - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
install:
  - yarn install
before_script:
  - npm test
  - gulp
  - cd dist
  - yarn install
script:
  - npm test
  - cd ..
before_deploy:
  - gulp preBuild
  - cd dist
deploy:
  edge: true
  cleanup: false
  on:
    branch: master
    tags: true
    condition: $TRAVIS_NODE_VERSION = 10.12
  tag: latest
  provider: npm
  email:
    secure: EoQODOwWH9ILqOx/a82ToevtRgtK+t+5y6lKEi8q1Qhoc+KeoffQYgtDWXDAva+goAs1OPk0NAdmlOHb/9z5xKArypz96JsOfabisJrkOLbiRHm3ZJ60+EtftXIKvMVVDeaiTmE3AbqGgptTvIW4aAHjtisw/7nY7S3FEzgcfbxjndC+oMtp7WZY9iry/ypQdvKr1HG+5J4ne/6IXYaKYlWFHV23H+OjTcfGsVm1PITFAN8Vhgtp3sh22huBH+2NhO/vQkBomwPUIk5xBkCnLTbARWMQaYprCmdRwZH5F+qiQd1oVqBrrgaENGErEjb8qYNqiH5NPXAVnVYdmA6ya/MO+OaFEBAkRrfSk9J0bw7UhcsAP0PKThMIMED2324XW8kxeJccpdzwFt1Tx+yrM/Sq6wdQLaq9ahamLj9cBudjCiUZvbVnSxroyzZ37s5GjKFvMXlG8a62pVQzRq31PG4OF6HMnetEhsEZmAhgyBlOy2AX+blRdIwgS/GrWyM680/QMoS7FYrUQtt011/jaHFd0PYg6jT3PH9iqncAfv9hwOPL4qevQ3Tuav5g+Mm6m8e3Rt8ZKgQiUEX+NJdrwChrO1nGWdNwOjXPSrpcoEolgx0H75wmTKrvPMuag3EziUPjMHbX7jlIxkJQa51E/74V00t9s9UhYZe2X5WbaxE=
  api_key:
    secure: G7uvY/Hz21Pk58B4nNv9xtY7fG8aHGglJ33cc6iKXju3lVi/1PLsYd5nL+DozrtncGBe08Vk05ydtaJm+ZPzYU5nOc4IeMTYsPSySJ4FkViKZwEdAw/36YJ3kyg/ix32Hf/cARApXOY1Ugo+bmyf7DgHKnzzZ2buJIzZj4+gWDrB/6KGObNAXxPAtPvamOh0APinkmk35WHB839U2hTpls+3FEB/ZTqlVktmL4OzFJTvjY5NKk5p5pS1LCDnPFSxwMP4XDFQqJheYEutkN5DEsQLuGrckD4EtlHesUMIVzRx4hy0OJ9ZmfVowsoTsnF4knCF7H6OCgvkQtiaKrUdzrCrWAf5bhh0ICO75GtjqSi5LFnyAnOmM6RcnW78u2unNJ87Trg7+2QUEzEowQP9EYIag0oBl6kHZ+fk9O6lAE5rr78XOq8U6GHOlxiTI3G/Y5HEt93sPd2Tl0Oxlo7fvtHyM2i9dHd7L6uvQt228XYwskr+wRi/z05agrrljtlk4EmPgxhKAQavtsK0d0eU+LLUnsE2AFMHvBYzL+lw3A+bxQwMYXUFcURy9csFRs74BUfK0j3uqVDrMdRe3uOOABnm6l7bv+5etlaM59qVb7Z6AAiKDSY1HcdwyJnJubn7cKUfeMo1gNZ3hJlOpBUti7EY2uQI30o9zbR6XzkIeQg=
